name: ⚙️ System Optimization
description: Performance oder systemd Service Optimierung
title: "[SYSTEM] "
labels: ["enhancement", "systemd", "performance", "needs-analysis"]
body:
  - type: textarea
    id: optimization_goal
    attributes:
      label: Optimierungsziel
      description: Was soll verbessert werden?
      placeholder: "z.B. Speicherverbrauch reduzieren, Startup Zeit verkürzen, Log Rotation..."
    validations:
      required: true

  - type: dropdown
    id: optimization_area
    attributes:
      label: Optimierungsbereich
      options:
        - "systemd Service Configuration"
        - "Memory Usage"
        - "CPU Performance" 
        - "Network Efficiency"
        - "Log Management"
        - "Error Handling"
    validations:
      required: true

  - type: textarea
    id: current_metrics
    attributes:
      label: Aktuelle Metriken
      description: Aktuelle Performance Werte (falls bekannt)
      placeholder: |
        Memory: ~50MB
        CPU: ~2% average
        Startup: ~5 seconds
        Logs: 10MB/week

  - type: textarea
    id: target_metrics  
    attributes:
      label: Ziel-Metriken
      description: Gewünschte Performance Werte
      placeholder: |
        Memory: <30MB
        Startup: <3 seconds
        Log Rotation: automatic