name: 💬 Telegram Bot Feature
description: Neue Telegram Bot Funktionalität
title: "[TELEGRAM] "
labels: ["enhancement", "telegram", "needs-analysis"]
body:
  - type: markdown
    attributes:
      value: |
        ## Telegram Bot Feature Request
        Beschreibe neue Funktionalität für den Telegram Bot.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Beschreibung
      description: Was soll der Bot können?
      placeholder: "z.B. /status Command für Service Health, /connections für manuelle Abfrage..."
    validations:
      required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Typ
      options:
        - "New Command (/command)"
        - "Notification Enhancement"
        - "Interactive Feature"
        - "Reporting Feature"
        - "Admin Feature"
    validations:
      required: true

  - type: textarea
    id: user_story
    attributes:
      label: User Story
      description: Als [Nutzer] möchte ich [Funktionalität] um [Nutzen]
      placeholder: "Als Bahnreisender möchte ich /status eingeben um den aktuellen Service Status zu sehen"

  - type: dropdown
    id: priority
    attributes:
      label: Priorität
      options:
        - "High - Wichtig für tägliche Nutzung"
        - "Medium - Nice to have"
        - "Low - Future Enhancement"
    validations:
      required: true